### ISSUE TITLE
Problem installing biobakery tool suite on Mac

### ISSUE THREAD

**Issue by ETaSky** [biobakery/homebrew-biobakery#4]
Hello,
I got following output while installing biobakery tool:
==> python2 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/strainphlan/2.6.0/libexec/vendor --single-version-exte
Last 15 lines from /Users/wangj50/Library/Logs/Homebrew/strainphlan/09.python2:
2017-06-13 10:07:06 -0400

python2
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/strainphlan/2.6.0/libexec/vendor
--single-version-externally-managed
--record=installed.txt

I don't know if this is an error or not, but it seems the tools were not successfully installed. I followed all instructions and tried on both installing the whole suite, or individual tool (e.g. lefse). Please help and thank you very much!

Jincheng

**Comment by ljmciver** [comment]
Hi Jincheng - That does not look like an error message. Maybe there is one in the log file? Can you let me know the command you ran and possibly provide the full output running with --verbose? Also let me know which tools you tried to install and those that do/don't work. Then I can help debug. 

Thanks!
Lauren

**Comment by ETaSky** [comment]
@ljmciver Hi Lauren, thank you for your reply. I am just trying to install lefse. I have installed homebrew, and then brew tap biobakery/biobakery, and then brew install lefse.
Then the output is:

wangj50@DOMINM05-I27-01:~$ brew install lefse
==> Installing lefse from biobakery/biobakery
==> Downloading https://bitbucket.org/nsegata/lefse/get/e3cabe93a0d1.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse-1.0.0-dev-e3cabe9.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse--numpy-1.11.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/wangj50/Library/Logs/Homebrew/lefse/01.python2:
2017-06-14 10:56:57 -0400

python2
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec
--single-version-externally-managed
--record=installed.txt

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues

Given this output, I don't think it has been installed. I was wondering if this helps.
Thanks!
Jincheng

**Comment by ljmciver** [comment]
Thank you for the additional information. Can you run again with the "--verbose" flag?
$ brew install leftse --verbose
This output will help identify the error. Also can you check you have python2 installed?
$ python2 --version

Thank you,
Lauren

**Comment by ETaSky** [comment]
@ljmciver Thanks!
I am using Mac which has python 2.7.10 pre-installed. And since you were specifically asking about python2, I guess if that is the problem. Because python2 is not a command on my machine. Should I create an alias to python or anything else should I do?
 
The --verbose output:
==> Installing lefse from biobakery/biobakery
==> Downloading https://bitbucket.org/nsegata/lefse/get/e3cabe93a0d1.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse-1.0.0-dev-e3cabe9.tar.gz
==> Verifying lefse-1.0.0-dev-e3cabe9.tar.gz checksum
tar xzf /Users/wangj50/Library/Caches/Homebrew/lefse-1.0.0-dev-e3cabe9.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse--numpy-1.11.0.tar.gz
==> Verifying lefse--numpy-1.11.0.tar.gz checksum
tar xzf /Users/wangj50/Library/Caches/Homebrew/lefse--numpy-1.11.0.tar.gz
==> python2 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec --single-version-externally-managed --record=installed.txt
Failed to execute: python2

==> Formula
Tap: biobakery/biobakery
Path: /usr/local/Homebrew/Library/Taps/biobakery/homebrew-biobakery/lefse.rb
==> Configuration
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4d4594cd517f56cfa30bc04aec1a2188223c0771
Core tap last commit: 64 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/readline:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: biobakery/biobakery/lefse 1.0.0-dev-e3cabe9 did not build
Logs:
     /Users/wangj50/Library/Logs/Homebrew/lefse/00.options.out
     /Users/wangj50/Library/Logs/Homebrew/lefse/01.python2
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues

**Comment by ljmciver** [comment]
Thank you for running with verbose and checking on python2. If you install python with homebrew, you should have python2 ("brew install python"). Alternatively you could create an alias as you suggested if your current install is python2 (from python to python2). Both options should resolve the error you are seeing when installing lefse. 

Thank you,
Lauren

**Comment by ETaSky** [comment]
@ljmciver Hello, thanks! I tried both methods (alias) and "brew install python". But still, the same error occurred. python2 apparently installed because python2 now open python 2.7.13, and my original python is 2.7.10. Is it possible that homebrew installed python doesn't have setuptools installed? If so, I was wondering how I should install python package for homebrew python. Thanks!

**Comment by ljmciver** [comment]
Hi Jincheng - I believe brew python should also install pip and setuptools. If you think setuptools is not installed, you could install it with pip. Are you still seeing the error "Failed to execute: python2" or do you see a different error? If it is a different error, can you provide the new error?

Thanks!
Lauren

**Comment by ETaSky** [comment]
@ljmciver Hi Lauren, I am seeing the exact error as mentioned in previous posts. "Failed to execute: python 2". Thanks! Jincheng

**Comment by ljmciver** [comment]
Hi Jincheng, Do you see an error when running "python2 --version" from the command line?

Thanks!
Lauren

**Comment by ETaSky** [comment]
@ljmciver No error. It works. python2 is correctly installed.
Thanks!
Jincheng

**Comment by ljmciver** [comment]
Hi Jincheng, I updated the lefse formula to use "python" if it can't find the "python2" install. If you update your brew formulas (with "brew update") you should have the latest lefse. I believe this modification should resolve the error you are seeing with Homebrew unable to see the python2 install.

Thanks!
Lauren

**Comment by ETaSky** [comment]
@ljmciver Hi Lauren, Thanks! After this update, I got some progress but the installation is still failing. I identified the reason is that freetype is not installed.
Now I got following error:
==> Installing lefse from biobakery/biobakery
==> Downloading https://bitbucket.org/nsegata/lefse/get/e3cabe93a0d1.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse-1.0.0-dev-e3cabe9.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse--numpy-1.11.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec --single-version-externally-managed --record=installed.txt
==> Downloading https://pypi.python.org/packages/source/m/matplotlib/matplotlib-1.5.1.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse--matplotlib-1.5.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/wangj50/Library/Logs/Homebrew/lefse/02.python:
                 cairo: no  [cairocffi or pycairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues

It seems it is because of freetype. But when I tried to do brew install freetype, it said freetype 2.8 has already been installed. I don't know what I can do now.

Jincheng

**Comment by ETaSky** [comment]
To followup, I think my system has messed up. I installed miniconda to install QIIME 2. And now python points to the python in miniconda folder. I was wondering if this might be the reason. Thanks!

Jincheng

**Comment by ljmciver** [comment]
Hi Jincheng, Yes, I think that might be it! I have found that conda and homebrew do not seem to be compatible. If you can change your paths so that the miniconda paths are not included, then install the lefse formula with homebrew, I think it should resolve your errors.

Thanks!
Lauren

**Comment by ETaSky** [comment]
@ljmciver Hi Lauren, Thanks! I have changed the path but still not working. Right now, I am 80% sure what the problem is. It is most likely because the failsure of installing R dependencies in Mac. For example, I am trying to manually install rpy2, but I cannot build it or pip install it because it seems teh OSX build system "clang" doesn't support openmp right now. I am still trying to figure out a way to get it done. Do you have any suggestions? Perhaps you could share how you configure your system at the beginning if you are using a Mac.
Thanks!

Jincheng

**Comment by ljmciver** [comment]
Hi Jincheng, I am sorry I use Linux so I can't help much with Mac configuration. Do you have other compilers installed? If not, I think you can install them by installing the command line tools for Xcode. Then you should have all of the basic compilers if you need them from openmp. Which tools do you need to install? Are you just trying to install lefse? If so, what errors do you get when you run the brew lefse install now? 

Thanks,
Lauren

**Comment by ETaSky** [comment]
Hi Lauren, Thanks! I already installed Xcode. Right now, brew install lefse still produce following error:
==> Installing lefse from biobakery/biobakery
==> Downloading https://bitbucket.org/nsegata/lefse/get/e3cabe93a0d1.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse-1.0.0-dev-e3cabe9.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse--numpy-1.11.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec --single-version-externally-managed --record=installed.txt
==> Downloading https://pypi.python.org/packages/source/m/matplotlib/matplotlib-1.5.1.tar.gz
Already downloaded: /Users/wangj50/Library/Caches/Homebrew/lefse--matplotlib-1.5.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/lefse/1.0.0-dev-e3cabe9/libexec --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/wangj50/Library/Logs/Homebrew/lefse/02.python:
                 cairo: no  [cairocffi or pycairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/biobakery/homebrew-biobakery/issues

Even though I have added : depends_on "freetype" => :recommended in the lefse formulae.

I don't know what I can do right now.

Jincheng

**Comment by ljmciver** [comment]
Hi Jincheng - Can you run the following command to check that you have brew freetype installed "brew install freetype"? If it is not installed, that command should install it for you. Then can you run "locate freetype | grep ft2build.h"? This will find the freetype headers. Brew freetype should install the headers in a location that matplotlib can find but I have found on some systems this is not the case. Depending on where freetype is installed you might need a symbolic link so matplotlib can find it. Let me know the outputs of the commands and then I can help with the link if needed.

Thanks,
Lauren

**Comment by ETaSky** [comment]
@ljmciver Hi Lauren, I have already have freetype installed. I forgot to mention in previous post. And I knew the header is not in the right place. I tried to ln -s the header from /usr/local/include/freetype2 to /usr/local. However, even I tried to use sudo, it still said Operation not permitted.
In addition, I already have matplotlib installed separately on my system, and no errors.
Besides, the command locate freetype just returns that the locate database does not exist. Should I create it?
Thanks!

**Comment by ljmciver** [comment]
Hi Jincheng - For the symlink, I think it would be something like "ln -s /usr/include/freetype2/ft2build.h /usr/include/" . I think the final location should be /usr/include/ for matplotlib to find the libraries. Would you like to use lefse in biobakery instead of trying to install with brew? We have a VM with many tools installed (including lefse) that you can run with very few commands. If you would like to try this out, all documentation is located at [http://huttenhower.sph.harvard.edu/biobakery](http://huttenhower.sph.harvard.edu/biobakery) . 

Thanks!
Lauren

**Comment by ETaSky** [comment]
@ljmciver Thanks! My symlink command is correct. I just don't know why it doesn't work. I used the VM machine before. But I just have too many bioinformatics tools using VM. I'll try around and if nothing works, I'll either use VM or the galaxy server. Thanks!
Jincheng
